name: CI
on: push
jobs:
  upload-artifact:
    runs-on: self-hosted
    steps:
      - run: |
          echo -n 'hello world' > my-artifact.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-artifact.txt
          retention-days: 15

  download-artifact:
    needs: upload-artifact
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - run: |
          content=`cat my-artifact.txt`
          echo "Content: $content"
          if [[ "$content" != 'hello world' ]]; then
            echo 'Unexpected content'
            exit 1
          fi
